isplay_name: boltz-inference-endpoint
traffic_split:
  "0": 100
deployed_models:
  - display_name: boltz-model
    model: projects/kallogjeri-project-345114/g/locations/us-central1/models/boltz-model # Replace with your model resource ID, or remove to deploy directly from container
    container:
      image: us-central1-docker.pkg.dev/kallogjeri-project-345114/boltz-repo/boltz-image
      ports:
        - container_port: 8080
    traffic_split:
      "0": 100
    machine_spec:
      machine_type: n1-standard-4
volume_mounts:
  - mount_path: /boltz/predictions
    volume: predictions-volume
volumes:
  - name: predictions-volume
    empty_dir: {}